config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks'}
  devise_for :installs
  resources :users, only: [:show, :edit, :update]
  resources :tweets do
    resources :tweet_comments
  end
  resources :tweet_images
  resources :blogs
  resources :blog_comments
  resources :blog_iamges
  resources :likes
  root :to => 'tweets#index'
end

app/models/blog.rb
class Blog < ActiveRecord::Base

end

app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base

end

app/models/blog_image.rb
class BlogImage < ActiveRecord::Base

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :tweet, counter_cache: :likes_count
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    has_one :tweet_image, dependent: :destroy
    belongs_to :user
    validates_presence_of :user_id, :text
    has_many :tweet_comments
end

app/models/tweet_comment.rb
class TweetComment < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet_image.rb
class TweetImage < ActiveRecord::Base
  belongs_to :tweet
  has_attached_file :avatar,
                    styles:  { medium: "100×100", thumb: "100×100" }
  validates_attachment_content_type :avatar,
                                    content_type: ["image/jpeg", "image/jpg", "image/png"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

   # userがいなければfacebookアカウントでuserを作成するメソッド
  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        # userモデルが持っているカラムをそれぞれ定義していく
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.nickname = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider

        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        # user.skip_confirmation!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
      '/login'
  end

  def after_sign_in_path_for(resource)
      '/'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @tweets = Tweet.order("created_at DESC").page(params[:page]).per(5)
  end

  def create
    tweet = Tweet.create(post_category: params[:post_category], content_category: params[:content_category], text: params[:text], user_id: current_user.id)
    TweetImage.create(avatar: params[:avatar], tweet_id: tweet.id)
    redirect_to :root and return
  end

  def new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comments = @tweet.tweet_comments.includes(:user)
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.update(tweet_params)
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.user_id == current_user.id
      tweet.destroy
    end
  end

  private
  def tweet_params
      params.permit(:text, :post_category, :content_category)
  end

  def tweet_image_params
      params.permit(:image, :tweet_id)
  end

  def move_to_index
      redirect_to action: :index unless user_signed_in?
  end

  def create_params
    params.require(:tweet).permit(:text, :post_category, :content_category).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def create
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    current_user.update(update_params)
  end

  private
  def update_params
    params.require(:user).permit(:nickname, :text, :avatar)
  end

  def user_params
  params.require(:user).permit(:nickname, :password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blog_images_helper.rb
module BlogImagesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweet_comments_helper.rb
module TweetCommentsHelper
end

app/helpers/tweet_images_helper.rb
module TweetImagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/_index.html.erb
<div class="tweet_content top_content">
  <div class="tweet_header">
    <div class="tweet_image icon_image" style="background-image: url(<%= tweet.user.avatar.url(:medium) %>);"></div>
    <div class="tweet_user_info user_info">
      <span><%= link_to tweet.user.name, user_path(tweet.user) %></span>
      <time><%= time_ago_in_words tweet.created_at %></time>
    </div>
  </div>
  <div class="tweet_body">
    <div class="tweet_box">
      <span class="q">Q</span>
      <span class="tweet_text"><%= tweet.text %></span>
    </div>
    <div class="tweeted">
      <%= link_to "回答#{tweet.tweet_comments.count}件", tweet_path(tweet) %>
    </div>
    <%= form_tag(new_tweet_comment_path, method: :get, class: "tweet_submit") do %>
      <%= hidden_field_tag(:tweet_id, tweet.id) %>
      <%= submit_tag("回答する") %>
    <% end %>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="content_post" style="background-image: url(<%= tweet.tweet_image.avatar %>);">
  <div class="more">
  </div>
  <%= simple_format(tweet.text) %>
  <span class="name">
    <a href="/users/<%= tweet.user_id %>">
      <span>投稿者</span><%= tweet.user.nickname %>
    </a>
    <li class="detail">
        <%= link_to "詳細", tweet_path(tweet.id), method: :get %>
    </li>
  </span>
</div>

app/views/tweets/_tweet_comment.html.erb
<section class="col-md-12">
  <div class="sct_inner">
    <p><%= link_to tweet_comment.user.name, user_path(tweet_comment.user) %>さんの回答</p>
    <h4>→<%= tweet_comment.text %></h4>
  </div>
</section>

app/views/tweets/create.html.erb
<div class="contents row">
    <div class="success">
      <h4>
        投稿が完了しました。
      </h4>
      <a class="btn" href="/tweets">投稿一覧へ戻る</a>
    </div>
</div>

app/views/tweets/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h4>
      削除が完了しました。
    </h4>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <%= form_tag("/tweets/#{@tweet.id}", method: :patch ) do %>
  <h3>
    編集する
  </h3>
  <textarea cols="50" placeholder="投稿カテゴリを選択する" type="text" name="post_category"><%= @tweet.post_category %></textarea>

  <input placeholder="内容カテゴリを選択する" type="text" name="content_category"><%= @tweet.content_category %>

  <textarea cols="30" name="text" placeholder="例：気になる人からのLINEが帰ってこないです..." rows="7"><%= @tweet.text %></textarea>

  <input type="file" name="avatar">

  <input type="submit" value="更新する">
  <% end %>
</div>

app/views/tweets/index.html.erb
  <div class="contents row" >
    <% @tweets.each do |tweet| %>
    <%= render partial: "tweet", locals: { tweet: tweet} %>
    <% end %>
    <%= paginate(@tweets) %>
  </div>

app/views/tweets/new.html.erb
<div class="contents row">
  <%= form_tag('/tweets', :multipart => true, method: :post) do %>
    <h3>
      投稿しよう！
    </h3>
    <input placeholder="投稿カテゴリを選択する" type="text" name="post_category">
    <input placeholder="内容カテゴリを選択する" type="text" name="content_category">
    <textarea cols="30" name="text" placeholder="例：最近旦那の帰りが遅く..." rows="7"></textarea>
    <input type="file" name="avatar">
    <input type="submit" value="投稿する">
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="contents row">
  <div class="contents_post" style="background-image: url(<%= @tweet.tweet_image.image %>);">
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
    <div class="more">
      <ul class="more_list">
        <li>
          <%= link_to '編集', "/tweets/#{@tweet.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', "/tweets/#{@tweet.id}", method: :delete %>
        </li>
      </ul>
    </div>
    <% end %>
    <%= simple_format(@tweet.text) %>
    <span class="name">
      <a href="/users/<%= @tweet.user.id %>">
        <span>投稿者：</span><%= @tweet.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">

    <% if current_user %>
     <%= form_tag("/tweets/#{@tweet.id}/tweet_comments", method: :post) do %>
      <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
      <input type="submit" value="送信する">
    <% end %>
  <% end %>

  <div class="comments">
    <h4>＜コメント一覧＞</h4>
    <% if @tweet_comments %>
     <% @tweet_comments.each do |comment| %>
      <p>
        <strong><%= link_to comment.user.nickname, "/user/#{comment.user_id}" %></strong>
        <%= comment.text %>
      </p>
     <% end %>
    <% end %>
 </div>
</div>

app/views/tweets/update.html.erb
<div class="contents row">
    <div class="success">
      <h4>
        更新が完了しました。
      </h4>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/users/edit.html.erb
<div class="row form">
  <div class="col-lg-12">
    <%= form_for current_user do |f| %>
      <h4>プロフィール画像</h4>
      <div class="form-group file">
        <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      <h4>登録情報</h4>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :nickname, placeholder: "ニックネーム", class: "form-control" %>
        </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row form user_profile">
  <div class="col-lg-12">

    <h4><a>ユーザー名：<%= @user.nickname %></a></h4>

    <% if current_user.id == @user.id %>
      <div class="profile_edit">
        <%= link_to "プロフィールを編集する", edit_user_path(current_user), {:class => "btn btn-primary withripple" }%>
      </div>

      <%= form_for @user do |f| %>
          <div class="field">
          <%= f.file_field :avatar %>
          </div>
      <% end %>

    <% end %>
  </div>
</div>

app/views/users/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h4>プロフィールの編集が完了しました。</h4>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>